### ISSUE TITLE
i don't know why the problem is

### ISSUE THREAD

**Issue by DeveloperKubilay** [FabricMC/fabric-example-mod#254]
![Ekran görüntüsü 2023-06-09 104223](https://github.com/FabricMC/fabric-example-mod/assets/107062509/82a414a6-f98a-4403-9e63-fad2cfa3f600)
![Ekran görüntüsü 2023-06-09 104145](https://github.com/FabricMC/fabric-example-mod/assets/107062509/bff8cdd1-dd64-416c-847c-b0762f224409)
![1](https://github.com/FabricMC/fabric-example-mod/assets/107062509/7a4071a3-d65a-4bef-bba0-14c1a608c589)
Cannot resolve resource filtering of MatchingCopyAction. IDEA may fail to build project. Consider using delegated build (enabled by default).

**Comment by modmuss50** [comment]
This is caused by an intelij bug, you can ingore it.

👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
