### ISSUE TITLE
ITEM cannot be resolved or is not a field - error in code

### ISSUE THREAD

**Issue by Busaruba2011** [FabricMC/fabric-example-mod#73]
I am getting this error in my mod java file, here's the whole mod java file:
https://pastebin.pl/view/49b96942
Visual Studio Code, Windows 10
I'll try reinstalling JDK

**Comment by NikunjChiluvuri** [comment]
hello,
edit this code so that it works for you : 

package net.fabricmc.example;

import net.fabricmc.api.ModInitializer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class ExampleMod implements ModInitializer {
	
	public static final Item FABRIC_ITEM = new Item(new Item.Settings().group(ItemGroup.MISC));
	
	@Override
	public void onInitialize() {
		Registry.register(Registry.ITEM, new Identifier("modid", "ice_item"), FABRIC_ITEM);
	}
}

**Comment by NikunjChiluvuri** [comment]
maby you worte the imports wrong

**Comment by NikunjChiluvuri** [comment]
or try this 
change this :
public static final Item FABRIC_ITEM = new Item(new FabricItemSettings().group(ItemGroup.MISC));

to this : 
public static final Item FABRIC_ITEM = new Item(new Item.Settings().group(ItemGroup.MISC));

**Comment by Busaruba2011** [comment]
Sorted
